from sqlalchemy.orm import Session
from app.db import models
from app.services.embedding_service import search_internships
import google.generativeai as genai
from app.core.config import settings
import json

def get_candidate_profile_text(resume: models.Resume) -> str:
    parsed = resume.parsed_json or {}
    skills = ", ".join([s.get("name", "") for s in parsed.get("skills", [])])
    exp = " ".join([e.get("description", "") or e.get("title", "") for e in parsed.get("experiences", [])])
    proj = " ".join([p.get("description", "") or p.get("technologies", "") for p in parsed.get("projects", [])])
    
    text = f"""
    Skills: {skills}
    Experience: {exp}
    Projects: {proj}
    """
    return text

def perform_matching(db: Session, user_id: str):
    # 1. Get latest resume
    resume = db.query(models.Resume).filter(models.Resume.user_id == user_id, models.Resume.is_active == True).first()
    if not resume:
        return []
    
    # 2. Convert candidate to semantic string
    candidate_text = get_candidate_profile_text(resume)
    
    # 3. Search ChromaDB
    results = search_internships(candidate_text, n_results=5)
    
    matches = []
    if not results or not results['ids'] or len(results['ids'][0]) == 0:
        return []
        
    internship_ids = results['ids'][0]
    distances = results['distances'][0]
    
    for i, intern_id in enumerate(internship_ids):
        # Fetch from DB
        internship = db.query(models.Internship).filter(models.Internship.id == intern_id).first()
        if not internship: continue
        
        # Calculate scores. Chroma uses L2 distance by default.
        # Lower distance = higher similarity.
        # Convert distance to a 0-100 similarity score roughly
        similarity_score = max(0, 100 - (distances[i] * 50))
        
        # 4. Generate grounded match explanation using LLM
        explanation, matched_skills, missing_skills = generate_match_explanation(candidate_text, internship)
        
        # Save match to DB
        match = models.Match(
            user_id=user_id,
            internship_id=internship.id,
            similarity_score=similarity_score,
            total_score=similarity_score, # Can add structural score later
            matched_skills=json.dumps(matched_skills),
            missing_skills=json.dumps(missing_skills),
            explanation=explanation
        )
        db.add(match)
        db.commit()
        db.refresh(match)
        
        matches.append({
            "internship": internship,
            "match_details": match
        })
        
    return matches

def generate_match_explanation(candidate_text: str, internship: models.Internship):
    if not settings.LLM_API_KEY:
        return "Match generated by semantic similarity.", [], []
        
    prompt = f"""
    Compare the candidate's profile with the internship requirements.
    Identify matched skills, missing skills, and provide a short concise explanation of why they are a match.
    DO NOT invent skills. Base it purely on the text.
    
    Candidate Profile:
    {candidate_text}
    
    Internship Title: {internship.title}
    Internship Requirements: {internship.required_skills} {internship.preferred_skills}
    Internship Description: {internship.description}
    
    Return output EXACTLY in this JSON format:
    {{
        "explanation": "Short 2 sentence explanation",
        "matched_skills": ["skill1", "skill2"],
        "missing_skills": ["skill3"]
    }}
    """
    
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)
        text = response.text.replace("```json", "").replace("```", "").strip()
        data = json.loads(text)
        return data.get("explanation", ""), data.get("matched_skills", []), data.get("missing_skills", [])
    except Exception as e:
        print(f"Error generating explanation: {e}")
        return "Semantic match found.", [], []
